### PR TITLE
Fixed "Select all"

### PR DESCRIPTION
**Pull request by dg-wfk**
Was not working due to missing "true" parameter.

### CODE REVIEW

**Comment by wavexx** [comment]
Which browser is causing the issue?

Note that normally selectAll also unchecks all boxes when switched off (it uses the state of the checkbox itself). Setting "true" manually will break this.

**Comment by dg-wfk** [comment]
It is not the "select/deselect all" checkbox which is not working. It is the "Select All" button!
The function selectAll needs a boolean "true" parameter to select all. If the parameter is omitted (that is the case) or boolean "false" it deselects all.
The checkbox on the other hand sends its own checked state with "this.checked" as parameter.

**Comment by wavexx** [comment]
On 05/02/16 20:53, dg-wfk wrote:
> It is not the "select/deselect all" checkbox which is not working. It is
> the "Select All" button!

My bad.

Still, can you roll up all the changes in a single pull request?

**Comment by dg-wfk** [comment]
Um, good question. I did it via the web-ui on github and could not find a way to change four files in one request. I think I have to install git on my server at work and use the shell to do that. But I will not be able to do that before Tuesday.

**Comment by wavexx** [comment]
Committed manually

**Pull request closed without merging**
