### PR TITLE
Minor login fix & corruption avoidance

### PR DESCRIPTION
**Pull request by beuss**
Focusing the username fields currently implies to skip all languages links using tab. First patch adds a tabindex & autofocus in login field. Did not modified other pages since they seem more likely to be used through mouse (at least in my case :-) )
Second one fixes a warning on ob_end_flush in the file download code. Had no time to investigate why this ob_end_flush is there and why a warning is emitted but since I needed to download uncorrupted files I just silented it out.

### CODE REVIEW

**Comment by wavexx** [comment]
ob_end_flush is there to disable output buffering while streaming the data.
It's not strictly necessary, but could you post the output of the warning?
Maybe output buffering wasn't started correctly and/or is disabled?
This would be important to know.

It's more correct to disable error output to the client for the entire length of the stream instead of silencing it.

**Comment by beuss** [comment]
Sorry for the very long delay, the notification mail was lost.
Warning is
Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush. in ticketr.php on line 82
This seems logical since there's no call to ob_start() anywhere. Maybe you're using a box with output_buffering = On ?
A nicer patch would be if(ob_get_length() > 0) ob_end_flush()
But the error silencing should be sufficient since it is not an error per se

**Comment by wavexx** [comment]
I'd rather take the second in this case. If you can amend the commit, I'll merge it. In this case, I'd like to get any warning about non-started buffering (if it's going to happen by mistake), and not silence them.

**Comment by beuss** [comment]
OK fixed the patch accordingly
Also removed the autofocus stuff to put it in a separate PR

**Comment by wavexx** [comment]
It occurred to me that's still not a proper fix. It doesn't disable output buffering if that was actually on sitewide, but no output was emitted. Explicitly calling ob_start is probably a better idea, and I'm looking into it now.

**Comment by wavexx** [comment]
Ok, I believe I pushed a better approach to it. For pages starting a session, we always start buffering unless already enabled sidewide. This should remove the need for this fix, while guaranteeing that buffering will be disabled while the output is sent.

Could you give it a try?

**Comment by beuss** [comment]
well, with the check of ob_level() before flushing we were disabling output buffering if enabled site wide (because in that case ob_level() is 1)
But indeed your fix also works

**Comment by wavexx** [comment]
On Fri, Apr 29 2016, Sébastien Le Ray <notifications@github.com> wrote:
> well, with the check of ob_level() before flushing we were disabling output buffering if enabled
> site wide (because in that case ob_level() is 1)
> But indeed your fix also works

True, but for general output you want output buffering on at all times
(for several performance reasons).

In fact, I assumed that it was always on before, probably wrongly.
Reading/outputting the file is the only exception.

Did you have a reason to disable output buffering sitewide that this
approach would defeat?

**Comment by beuss** [comment]
Well, Off is the default value
Moreover if I'm not mistaken disabling it at php level might not be an issue if you use other filters like eg mod_deflate

**Comment by wavexx** [comment]
Disabling ob at the PHP level will always be possible, but in this case all ob_* functions to be a no-op.

**Comment by wavexx** [comment]
Any other fix that you'd like to see rolled into 0.17.1?

**Comment by beuss** [comment]
fine for me :) thanks

**Pull request closed without merging**
