### PR TITLE
Update of french translation

### PR DESCRIPTION
**Pull request by beuss**
Those three commits fix existing translations and add new ones from 0.18

### CODE REVIEW

**Comment by wavexx** [comment]
Thanks for this. Did you actually had a chance at testing the new grants and multi-file uploads?

**Comment by beuss** [comment]
Just upgraded to 0.18 to test multiple file uploads actually :-)
First quick was fine
With new grants I got immediate purge but I guess this was caused by missing $defaultGrant(LastUlDays|MaxUl) in my config.php
Just sent a mail on the mailing list to know if you'd be interested by some boostrap themed UI (I could take time to do it but only if it has a chance to be merged)

**Comment by wavexx** [comment]
On Tue, Jul 11 2017, Sébastien Le Ray wrote:
> Just upgraded to 0.18 to test multiple file uploads actually :-) First
> quick was fine With new grants I got immediate purge but I guess this
> was caused by missing $defaultGrant(LastUlDays|MaxUl) in my config.php

Ok, this needs to be fixed though!

> Just sent a mail on the mailing list to know if you'd be interested by
> some boostrap themed UI (I could take time to do it but only if it has
> a chance to be merged)

Bootstrap how, roughly? It's too generic for me :)

But in general, yes. I'm not too fond of the current theme, but I'm not
too fond of bootstrap super-whitespace-margins either ;)

**Comment by beuss** [comment]
Just use default bootstrap theme (with maybe customized colors?) for overall layout & tooltips

**Comment by wavexx** [comment]
On Tue, Jul 11 2017, Sébastien Le Ray wrote:
> With new grants I got immediate purge but I guess this was caused by
> missing $defaultGrant(LastUlDays|MaxUl) in my config.php

Ok, discovered the issue. Typo in the expiration logic, causing the
wrong variable to be used.

**Pull request merged**
