### PR TITLE
Docker basic stuff for image creation

### PR DESCRIPTION
**Pull request by droberin**
- Added Dockerfile for easy docker image creation.
- Added docker folder including some configuration scripts and user management scripts

### CODE REVIEW

**Comment by droberin** [comment]
Better structure, also new features:
- modification of upload size limitations from envionment variables
- added a configuration folder for htaccess and config.php

**Comment by droberin** [comment]
Hey. I did this Docker stuff we talked about through email. If there something wrong about it? It's been 4 months without any feedback

**Comment by wavexx** [comment]
On Tue, Jul 11 2017, Roberto Salgado wrote:
> Hey. I did this Docker stuff we talked about through email. If there
> something wrong about it? It's been 4 months without any feedback

I didn't have time to touch DL in a while.

Plus, I have exactly zero knowledge about docker. I'm not sure I can
maintain or answer questions about that. Wouldn't it make sense to
provide the docker file directly on hub.docker.com?

Also, one of our colleagues here is doing a prototype client for
android, so my hope is to wait until it's usable and get that into the
next release as well.

**Comment by droberin** [comment]
Sure, I made an automated build now from my fork. :+1:

**Pull request closed without merging**
